# Generated by Django 5.2.14 on 2026-05-21 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('developers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('linguagem', 'Linguagem'), ('framework', 'Framework'), ('banco_de_dados', 'Banco de dados'), ('cloud', 'Cloud'), ('devops', 'DevOps'), ('automacao', 'Automação'), ('low_code', 'Low-code'), ('ferramenta', 'Ferramenta'), ('metodologia', 'Metodologia'), ('comunicacao', 'Comunicação'), ('lideranca', 'Liderança'), ('didatica', 'Didática'), ('organizacao', 'Organização'), ('resolucao_problemas', 'Resolução de problemas'), ('trabalho_equipe', 'Trabalho em equipe'), ('mentoria', 'Mentoria'), ('documentacao', 'Documentação')], max_length=50)),
                ('type', models.CharField(choices=[('hard', 'Hard Skill'), ('soft', 'Soft Skill')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeveloperSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, 'Estou aprendendo'), (2, 'Sei o básico'), (3, 'Uso em tarefas reais'), (4, 'Tenho experiência avançada'), (5, 'Posso ensinar ou mentorar')], default=1)),
                ('is_learning', models.BooleanField(default=False)),
                ('is_available_to_help', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('years_of_experience', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developer_skills', to='developers.developer')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developer_skills', to='skills.skill')),
            ],
            options={
                'ordering': ['-level', 'skill__name'],
                'unique_together': {('developer', 'skill')},
            },
        ),
    ]
